# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190504_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
