# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190504_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='event-images'),
        ),
    ]
