# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trustee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='trustees')),
                ('bios', models.TextField()),
            ],
        ),
    ]
